- When you want to send the exception object back to the caller, use the C# throw() statement.